### ISSUE TITLE
Error:Peer server error [Error: Could not get an ID from the server.] Help me

### ISSUE THREAD

**Issue by buiminhduc1995** [metehankurucu/peer-api#1]

**Comment by rameshjega** [comment]
i also facing the same issue in 


its working :
export const PEER_SERVER_HOST = 'webrtc-peer-server.herokuapp.com';
export const PEER_SERVER_PORT = '';
export const PEER_SERVER_PATH = '/peerjs'; 

its not working
export const PEER_SERVER_HOST = '192.168.43.29';
export const PEER_SERVER_PORT = '9000';
export const PEER_SERVER_PATH = '/peerjs'; 


can you please share me the peer-server code inside of this domain "webrtc-peer-server.herokuapp.com"



i get this error from peer server but server is working
![Screenshot from 2021-08-27 15-21-42](https://user-images.githubusercontent.com/52094962/131108866-0cd6f942-b39f-4ed7-84ae-8dd40a8ffe58.png)

 Emitted 'error' event at:
     at WebSocketServer.<anonymous> (/home/ec2-user/workplace/peer-server/node_modules/peer/dist/src/instance.js:54:13)
     at WebSocketServer.emit (events.js:315:20)
     at WebSocketServer._onSocketError (/home/ec2-user/workplace/peer-server/node_modules/peer/dist/src/services/webSocketServer/index.js:51:14)
     at WebSocketServer.<anonymous> (/home/ec2-user/workplace/peer-server/node_modules/peer/dist/src/services/webSocketServer/index.js:23:55)
     at WebSocketServer.emit (events.js:315:20)
     at Server.emit (events.js:315:20)
     at emitErrorNT (net.js:1340:8)
     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
   code: 'EADDRINUSE',
   errno: -98,
   syscall: 'listen',
   address: '::',
   port: 4000
 }

**Comment by buiminhduc1995** [comment]
What platform are you using?

**Comment by beheobong** [comment]
I using centos 7 to build server. It is the same error. Please help me!

**Comment by beheobong** [comment]
Oh, i resolve it. kaka. 
![Screenshot 2022-10-20 103403](https://user-images.githubusercontent.com/53457593/196850347-6fe00a94-ee40-471e-8f06-316194afb4e0.png)
change code in react-native app the same above picture => it working
